### ISSUE TITLE
https://paste.laravel.io/ got hacked

### ISSUE THREAD

**Issue by Hapistorique** [laravelio/pastebin#33]
Hi,

I just used paste.laravel.io and got redirected to this paste after saving, forking my own paste, and saving again : 

https://paste.laravel.io/bkzXL

Tried it on a Windows 10 machine with Chrome, and Debian + Firefox on a VM.
Got redirected once, each time. But once it showed up, it didn't do it anymore.

**Comment by prophetnite** [comment]
I would check your debian server configurations first.  I have been running it for some time now.  I have yet to find any glaring issues with its security that would allow hackers to run rampant in my system.

**Comment by Hapistorique** [comment]
I don't host the script myself, I mean https://paste.laravel.io/ has been hacked

**Comment by driesvints** [comment]
So what happened is that there's a race condition where double hashes are created for pastes so you were redirected to an older paste with the same hash. I'll implement a fix so this won't happen again.

I've deleted above paste. Please remember that all pasted content is publically available as said in the sidebar.

No-one got hacked but thanks for reporting this!

**Comment by driesvints** [comment]
I've replaced the hashids with UUIDs. Longer but ensures they're always unique. Removed all older duplicate records and added a unique index on the hash column.
