### ISSUE TITLE
View old pastebin code

### ISSUE THREAD

**Issue by shiroamada** [laravelio/pastebin#36]
Is the database still available?
I went to 
https://laravel.io/forum/02-10-2014-storing-configuration-on-database
and I found the pastebin link:-
http://laravel.io/bin/WjY

But it does not work, it should migrate with any redirect for old data.

**Comment by driesvints** [comment]
Ah, that's because the location of the pastebin got changed. I just added a change which properly redirects. 

However, it seems that this particularly paste was removed in the meantime.
